---
- hosts: test
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"

  tasks:

  - name: Create file
    file:
      path: "/etc/devops.txt"
      state: touch

  - name: Insert a line at the end of a file
    lineinfile:
      path: "/etc/devops.txt"
      line: "Martin was here 2018!"
